### ISSUE TITLE
Have appointment till end of time and to certain date?

### ISSUE THREAD

**Issue by davidbuckleyni** [SergeyBarskiy/RecurrenceCalculator#10]
Curious If you want it to go to an end date do you just simply remove occurrences below
Some calendar systems allow you do to till forever until the appointment is removed how does this happen.
     
     private AppointmentRecurrence CreateWeeklyRecurrence()
    {
        return new AppointmentRecurrence
       {
        RecurrenceType = RecurrenceType.Weekly,
        Interval = 2,
        Sunday = false,
        Monday = false,
        Tuesday = true,
        Wednesday = false,
        Thursday = true,
        Friday = false,
        Saturday = false,
        StartDate = startDate,
        Occurrences = 5
    };
}

And instead do do this

     private AppointmentRecurrence CreateWeeklyRecurrence(DateTime starDate, int interval, RecurrenceType  )
        {
            return new AppointmentRecurrence
            {
                RecurrenceType = RecurrenceType.Monthly,
                Interval = 1,
                Sunday = false,
                Monday = false,
                Tuesday = true,
                Wednesday = false,
                Thursday = true,
                Friday = false,
                Saturday = false,
                StartDate = starDate,
                EndDate = startDate.AddYears(1)
                
            };
        }

How would i also read back the appointments to place into a calendar have you some examples of that

**Comment by SergeyBarskiy** [comment]
I am not sure I follow the question.  Right now you have to set an end date, but if you show data to a user, you need that anyway.  If you a scrolling ui# you can call again on a scroll.

Sergey

**Comment by davidbuckleyni** [comment]
Basically some clanedards an Iphone has 

Every Day
Every Week 
Every 2 weeks 
Every Month
Every Year

Sometimes only a time is set not an end date? or do they do a default end date?

**Comment by SergeyBarskiy** [comment]
Not sure how the do it.  But it does not matter because you only need to care about events in visible calendar weeks.  And when you create reminders you care about today and maybe tomorrow.  In other words you compute events always for some date range you care about.

Sergey

**Comment by davidbuckleyni** [comment]
Is their any chance this libary be ever updated its quite old now

**Comment by SergeyBarskiy** [comment]
Is there a bug there?  Or some missing feature?  I just think it's feature complete.  So not dead, but done.

Sergey

**Comment by davidbuckleyni** [comment]
Just saying updating to more recent .net 6 etc ur nugets fail on latest xamrain

**Comment by SergeyBarskiy** [comment]
Thanks.  I'll work on that.  Hopefully will have updated nuget in a week or so.

Sergey

**Comment by SergeyBarskiy** [comment]
Looking again, the nuget is netstandard and can be used anywhere, .net 6 or anywhere else.  So, I do not see any reason to target specific framework.  Unless you have a compelling reason I am missing,@davidbuckleyni

**Comment by SergeyBarskiy** [comment]
I published version 1.0.6 today with .net 6 target in addition to net standard  @davidbuckleyni

**Comment by davidbuckleyni** [comment]
Thanks budy am sure am not only one uses it.
