### ISSUE TITLE
Monthly Recurrence Calculation Issue

### ISSUE THREAD

**Issue by Defstun** [SergeyBarskiy/RecurrenceCalculator#18]
Hi Sergey,

We have come across an issue in the monthly recurrence calculation.

https://github.com/SergeyBarskiy/RecurrenceCalculator/blob/81c80781ea915025a8a4663b677794e3f589e4c1/RecurrenceCalculator/Calculator.cs#L136-L157

### Explanation of the Issue

Before I explain what the code is doing, I'll give an example of the problem with some data (there is also an incoming PR with a failing test so you can just run it).

Consider we have set the following values on IRecurrence:

```
recurrence.StartDate = 31/01/2023
interval = 1
recurrence.DayOfMonth = 18
Occurrences = 1
```

I would expect the following:

When line 141 has executed, date should be equal to 01/02/2023 and when the method GetMonthlyRecurrenceOccurrences has finished, I would expect that we have one date of 18/02/2023.

The date is returned from the method is 29/01/2023.

### Why I think it's returning that value.

AddMonths() will pass the result to AddDays() but the expression inside the AddDays() does NOT see that value, it still has a reference to "date" on line 138. The date declared on line 138 does not get updated until the whole line (141) has finished executing, which is too late for your expression. You need the new date.Day from the result of AddMonths().

**Steps:**

https://github.com/SergeyBarskiy/RecurrenceCalculator/blob/81c80781ea915025a8a4663b677794e3f589e4c1/RecurrenceCalculator/Calculator.cs#L138-L142

1. AddMonths() evaluates first and changes the date to 28/02/2023, that is passed through to AddDays()
2. The expression inside AddDays() is evaluated, date.Day inside that expression has not been updated yet so it's still set to 31 (the original reference on line 138), so we take that day value of 31, minus 1 makes it 30 then multiply by -1 makes it -30.
3. AddDays() evaluates and subtracts -30 from the date (28/02/2023) making it 29/01/2023 which is incorrect.

There is a fix for this, you can either switch the AddDays and AddMonths around so that AddDays(expression) is evaluated first:

`date = date.AddDays(-1 * (date.Day - 1)).AddMonths(recurrence.Interval);`

This works because the date.Day reference is ok to use at this point because we haven't tried to modify it yet.

Or you can split them onto multiple lines:

```
date = date.AddMonths(recurrence.Interval);
date = date.AddDays(-1 * (date.Day - 1));
```

Either of those will produce the correct result.

I will send a PR for this that has a failing test, just to aid communication of the problem and clarify anything above that was unclear.

If you agree that the issue is valid and like one of the suggested fixes above, I can send a second PR with the fix if that would help.

I haven't checked the whole year but I have a feeling it only occurs in Feb because of it being a short month of 28 days.

Kind Regards,
Mark

**Comment by SergeyBarskiy** [comment]
Thank you for reporting, @Defstun Mark!.  Version 3.0.2 I just published contains the fix.

**Comment by Defstun** [comment]
Thanks for a speedy fix and release!
