### ISSUE TITLE
Should_Generate_Daily_Weekday_Recurrences_With_End_Date incorrect dates

### ISSUE THREAD

**Issue by Picklepants** [SergeyBarskiy/RecurrenceCalculator#2]
Change the test to have a start date of 2/24/16 and an end date of 3/26/2016, put a break point on 
var occurrences = _calendarUtility.CalculateOccurrences(recurrence).ToList(); 

See that the list of occurrences are not correct.

The interval does not appear to work at all. 
You can see the same outcome in this other test as well:
Should_Generate_Daily_Weekday_Recurrences_Without_End_Date()

You could also just change the test to use the year 2016 while leaving the month and day dates alone, you will see there is still a problem with the interval not working.

**Comment by Picklepants** [comment]
The issue is with this piece of code in calculator.cs
 ```
date = IsWeekdaySet(recurrence)
                    ? (date.AddDays((date.DayOfWeek == DayOfWeek.Friday) ? 3 : 1))
                    : date.AddDays(recurrence.Interval);
```

I fixed my issue by flip flopping the immediate if, but it still doesn't make all tests pass.
```
date = IsWeekdaySet(recurrence)
                    ? date.AddDays(recurrence.Interval)
                    : (date.AddDays((date.DayOfWeek == DayOfWeek.Friday) ? 3 : 1));
```

**Comment by Picklepants** [comment]
I think this may actually be the fix.
```
date = IsWeekdaySet(recurrence)
                    ? (date.AddDays((date.DayOfWeek == DayOfWeek.Friday) ? 2 + recurrence.Interval : recurrence.Interval))
                    : date.AddDays(recurrence.Interval);
```

**Comment by SergeyBarskiy** [comment]
Could you provide some details as to what the recurrence looks like?  Maybe a test to reproduce the issue?  Weekday recurrences should not use interval, as the event occurs on every weekday?

**Comment by Picklepants** [comment]
What if you want every weekday that is every 2 days, meaning you want: Fri, Tues, Thurs, Mon, Wed, Fri, Tues, Thurs, Mon, Wed

If you take a look at rrule and go to their demo page, then to the rrule string tab and paste this:
FREQ=DAILY;COUNT=10;INTERVAL=2;WKST=SU;BYDAY=MO,TU,WE,TH,FR

You can see what I am trying to accomplish. 

I have forked your code and wrote the test and fix on my fork, in order to test on yours just change the dates in your test, change start date to use a 2016 date, and change the end date to use a 2016 date, then place a break point before your assert and you will see the dates are wrong because it gives you every day but your assert shows that it respects the interval, you will see that not one of the daily tests work.
Also the unit test for a daily occurrence uses an interval so I thought it was meant to use it..

I am having issues attaching a zip to my post, are you able to look at my fork?

**Comment by SergeyBarskiy** [comment]
This is not a use case that Outlook supports.  You can pull up recurrence screen in it and take a look.  You cannot set an interval for weekday recurrence.  Hence the project does not support your use case.  If you want to add support for weekly/daily combination, which is what you are describing, feel free to submit pull request with tests,  I am sure other folks may want this.

**Comment by SergeyBarskiy** [comment]
This is not a use case that Outlook supports. You can pull up recurrence screen in it and take a look. You cannot set an interval for weekday recurrence. Hence the project does not support your use case. If you want to add support for weekly/daily combination, which is what you are describing, feel free to submit pull request with tests, I am sure other folks may want this.

**Comment by SergeyBarskiy** [comment]
This is not a use case that Outlook supports. You can pull up recurrence screen in it and take a look. You cannot set an interval for weekday recurrence. Hence the project does not support your use case. If you want to add support for weekly/daily combination, which is what you are describing, feel free to submit pull request with tests, I am sure other folks may want this.
