### ISSUE TITLE
order of date enumeration 

### ISSUE THREAD

**Issue by codeparksoftware** [SergeyBarskiy/RecurrenceCalculator#5]
Hello this is only question about order of date enumeration.
when ever I generate the recurrences should I order or is it already sorted ASC?
This is not bug. As far as I know Ienumerable does not guarantee to be ordered when I iterate the datas.
If I am wrong please correct me.
Thx in advance. @SergeyBarskiy

**Comment by SergeyBarskiy** [comment]
The dates are calculated in order, so naturally are sorted in ascending order.
