### ISSUE TITLE
Index

### ISSUE THREAD

**Issue by codeparksoftware** [SergeyBarskiy/RecurrenceCalculator#6]
Hello Dear Sergey,
Nowadays,I am inspecting your package. If your calculator can cover all of my requirements I will be able to use. I have a question. It is about "broken serial appointments".
Consider that the appointments sould be shown everyday but user deleted wednesday of  week for only next week. As you know we should not show this appointment for next week on wednesday. We have to ignore this. It is clear.
So Could you think to add ignorance list -should start from 1 because 0 is undefined in time-? in IRecurrence interface.
If you don't even do this I can cover but this is possible situation for all recurrence calculator app. It might be useful for every programmer who will use your package.
If you did not understand of if you have further question please let me know.
Best regards and wishes

**Comment by SergeyBarskiy** [comment]
I do not see a clear way to do this.  If you are keeping track of deleted appointments, you are already doing what you need.  Potentially, you could add a list of skipped recurrence numbers, but if recompute using any other start date, the result would be wrong.  So, unless you see a clear way do identify the skipped occurrences, I would prefer to keep API clean to match Outlook.

**Comment by codeparksoftware** [comment]
> but if recompute using any other start date, the result would be wrong.
Right. 
This is already exist in current situation. 
The programmers are responsible for this potential dangerous. In current  situation , we have to reorder the ignore list when start date changed,as well.

**Comment by SergeyBarskiy** [comment]
I am going to close the issue since there is no clear solution.  Feel free to open a new one once you know a clear way to achieve this,
