### ISSUE TITLE
Day property in IRecurrence interface

### ISSUE THREAD

**Issue by codeparksoftware** [SergeyBarskiy/RecurrenceCalculator#7]
I see the Day property in IRecurrence interface. But this property seems useless.  What exactly is your intention with this property. As far as I guess it indicates the appointment is all day event. Right?
If you really don't use why don't you eliminate it?
It has already unclear property definition.

![useless](https://user-images.githubusercontent.com/14142585/71962989-fcbc3800-31fa-11ea-961a-1209161b7946.PNG)

You stated Day of month. You have already one more DayOfMonth.
Sincerely greetings.

**Comment by SergeyBarskiy** [comment]
I removed the property and published new version.
Thanks.
