### ISSUE TITLE
Setting Days

### ISSUE THREAD

**Issue by codeparksoftware** [SergeyBarskiy/RecurrenceCalculator#9]
private AppointmentRecurrence CreateMonthlyRecurrence()
        {
            return new AppointmentRecurrence
            {
                RecurrenceType = RecurrenceType.Monthly,
                Interval = 3,
                DayOfMonth = 31,
                Sunday = false,
                Monday = false,
                Tuesday = true,
                Wednesday = false,
                Thursday = false,
                Friday = false,
                Saturday = false,
                StartDate = _startDate,
                Occurrences = 3
            };
        }
the day of the date of "2014,1,31" is Friday.
Why did you set only Tuesday?
It is emergency question.
Please let me know..
According to date  the Friday should be set.
But Tuesday is set

I think in monthly cases days has no deal. Right?

**Comment by SergeyBarskiy** [comment]
You are setting day to 31st, right?  So, the event will be on 31st.  If you look in outlook for monthly event, you cannot specify days of the week, if you specify day number, it is one or the other.  So, do not specify day of month, but specify instance,

**Comment by codeparksoftware** [comment]
> You are setting day to 31st, right? So, the event will be on 31st. If you look in outlook for monthly event, you cannot specify days of the week


This section right. But you pass the days as parameters right?


In fact that, This is not what I mentioned. I mean that when You set the date as "31.1.2014" and it  should be Friday not Tuesday according to calendar right?

But in test  class there are parameters and only tuesday true if you look above.
I did not understand why Tuesday true others are false. If you wanna pass day should be Friday.
Ok?

**Comment by SergeyBarskiy** [comment]
Sure, I guess.  I am kind of lost what you are asking / trying to do.  Tests are just tests.  Maybe include a screenshot of Outlook recurrence of your goal?

**Comment by codeparksoftware** [comment]
Unfortunately you did not understand me.
It is not relevant with me or Outlook.
private AppointmentRecurrence CreateMonthlyRecurrence()
{
return new AppointmentRecurrence
{
RecurrenceType = RecurrenceType.Monthly,
Interval = 3,
DayOfMonth = 31,
Sunday = false,
Monday = false,
**_Tuesday = true,_**
Wednesday = false,
Thursday = false,
Friday = false,
Saturday = false,
StartDate = _startDate,
Occurrences = 3
};
}
Why did you Set **_Tuesday_** as true?
It makes me confused.
I just wanna learn that.

**Comment by SergeyBarskiy** [comment]
Just a shortcut since I can use this for multiple tests.   If you are using day of month, day of week does not matter.

**Comment by codeparksoftware** [comment]
Allright when does make weekdays matter ?

**Comment by SergeyBarskiy** [comment]
Same place where it matters in Outlook, like weekly
